//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigNet.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestTestResult
    {
        public int LatestTestResultID { get; set; }
        public int SuiteId { get; set; }
        public int TestId { get; set; }
        public int TestResultId { get; set; }
        public string TestName { get; set; }
        public Nullable<System.DateTime> PassingFromDateTime { get; set; }
        public Nullable<System.DateTime> FailingFromDateTime { get; set; }
    
        public virtual Suite Suite { get; set; }
        public virtual Test Test { get; set; }
        public virtual TestResult TestResult { get; set; }
    }
}
