//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigNet.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuiteResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuiteResult()
        {
            this.TestResults = new HashSet<TestResult>();
            this.TemporaryTestResults = new HashSet<TemporaryTestResult>();
        }
    
        public int SuiteResultID { get; set; }
        public int SuiteId { get; set; }
        public System.DateTime SuiteResultStartDateTime { get; set; }
        public Nullable<System.DateTime> SuiteResultEndDateTime { get; set; }
        public int SuiteResultTypeId { get; set; }
    
        public virtual Suite Suite { get; set; }
        public virtual SuiteResultType SuiteResultType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryTestResult> TemporaryTestResults { get; set; }
    }
}
