//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigNet.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporaryTestResult
    {
        public int TemporaryTestResultID { get; set; }
        public int TestResultId { get; set; }
        public int SuiteResultId { get; set; }
        public int SuiteId { get; set; }
        public int TestResultTypeId { get; set; }
    
        public virtual SuiteResult SuiteResult { get; set; }
        public virtual Suite Suite { get; set; }
        public virtual TestResult TestResult { get; set; }
        public virtual TestResultType TestResultType { get; set; }
    }
}
