//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigNet.Database.EntityFramework
{
    using System.Collections.Generic;

    public partial class TestResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResult()
        {
            this.TestFailureDetails = new HashSet<TestFailureDetail>();
            this.TestFailureTypes = new HashSet<TestFailureType>();
            this.LatestTestResults = new HashSet<LatestTestResult>();
        }
    
        public int TestResultID { get; set; }
        public int TestId { get; set; }
        public int SuiteResultId { get; set; }
        public System.DateTime TestResultStartDateTime { get; set; }
        public System.DateTime TestResultEndDateTime { get; set; }
        public int TestResultTypeId { get; set; }
    
        public virtual SuiteResult SuiteResult { get; set; }
        public virtual Test Test { get; set; }
        public virtual TestResultType TestResultType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestFailureDetail> TestFailureDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestFailureType> TestFailureTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LatestTestResult> LatestTestResults { get; set; }
    }
}
