//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigNet.Database.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStepResult
    {
        public int TestStepResultID { get; set; }
        public int TestStepId { get; set; }
        public int TestResultId { get; set; }
        public System.DateTime TestStepResultStartDateTime { get; set; }
        public System.DateTime TestStepResultEndDateTime { get; set; }
        public int TestStepResultTypeId { get; set; }
    
        public virtual TestResult TestResult { get; set; }
        public virtual TestStep TestStep { get; set; }
        public virtual TestStepResultType TestStepResultType { get; set; }
    }
}
